# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: FaturaFlow API CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/teacher-schedules

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/teacher-schedules/node_modules
          key: modules-${{ hashFiles('**/package.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: backend/teacher-schedules/dist

  lint-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/teacher-schedules

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/teacher-schedules/node_modules
          key: modules-${{ hashFiles('**/package.json') }}
      - name: Lint
        run: npm run lint

  test-backend:
    if: github.actor != 'dependabot[bot]'
    needs: build-backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/teacher-schedules

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/teacher-schedules/node_modules
          key: modules-${{ hashFiles('**/package.json') }}
      - name: Tests
        run: npm run test
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./backend/teacher-schedules/test-report/report.html
